# this file replaces <root>/codecov.yml when building on the main repository and PRs
coverage:
  status:
    project: true
    patch: true
    changes: true

comment: off

codecov:
  # token from: https://codecov.io/gh/pytest-dev/pytest/settings
  # use same URL to regenerate it if needed
  token: "1eca3b1f-31a2-4fb8-a8c3-138b441b50a7"
