sudo: false
language: python
python:
    - '3.5'
install:
  - "pip install -U tox coveralls"
env:
  matrix:
    # note: please use "tox --listenvs" to populate the build matrix below
    - TESTENV=linting
    - TESTENV=py26
    - TESTENV=py27
    - TESTENV=py33
    - TESTENV=py34
    - TESTENV=py35
    - TESTENV=pypy
    - TESTENV=py27-pexpect
    - TESTENV=py27-xdist
    - TESTENV=py27-trial
    - TESTENV=py35-pexpect
    - TESTENV=py35-xdist
    # Disable py35-trial temporarily: #1989
    #- TESTENV=py35-trial
    - TESTENV=py27-nobyte
    - TESTENV=doctesting
    - TESTENV=freeze
    - TESTENV=docs

script:
  - tox -e $TESTENV
  - coverage report -m
  - coveralls
  #- coverage run --source=_pytest -m tox --recreate -e $TESTENV
  #- coverage report -m
  #- coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net#pytest"
    on_success: change
    on_failure: change
    skip_join: true
  email:
    - pytest-commit@python.org
