trigger:
- master
- features

variables:
  PYTEST_ADDOPTS: "--junitxml=build/test-results/$(tox.env).xml"
  python.needs_vc: False
  python.exe: "python"
  COVERAGE_FILE: "$(Build.Repository.LocalPath)/.coverage"
  COVERAGE_PROCESS_START: "$(Build.Repository.LocalPath)/.coveragerc"
  PYTEST_COVERAGE: '0'

jobs:

- job: 'Test'
  pool:
    vmImage: "vs2017-win2016"
  strategy:
    matrix:
      py27-nobyte:
        python.version: '2.7'
        tox.env: 'py27-nobyte'
        # Coverage for:
        # - test_supports_breakpoint_module_global
        # - test_terminal_reporter_writer_attr (without xdist)
        # - "if write" branch in _pytest.assertion.rewrite
        # - also for more stable(?) isatty in _pytest.terminal
        #   (according to https://codecov.io/gh/pytest-dev/pytest/pull/4858/src/src/_pytest/terminal.py).
        PYTEST_COVERAGE: '1'
      py34-xdist:
        python: '3.4'
        tox.env: 'py34-xdist'
        # Coverage for:
        # - _pytest.compat._bytes_to_ascii
        PYTEST_COVERAGE: '1'
      py35-xdist:
        python.version: '3.5'
        tox.env: 'py35-xdist'
        # Coverage for test_supports_breakpoint_module_global
        PYTEST_COVERAGE: '1'
      py36-xdist:
        python.version: '3.6'
        tox.env: 'py36-xdist'
        # Coverage for:
        # - _py36_windowsconsoleio_workaround (could also be py36+)
        PYTEST_COVERAGE: '1'
    maxParallel: 10

  steps:
  - task: UsePythonVersion@0
    condition: not(startsWith(variables['python.exe'], 'pypy'))
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: choco install vcpython27
    condition: eq(variables['python.needs_vc'], True)
    displayName: 'Install VC for py27'

  - script: choco install python.pypy
    condition: eq(variables['python.exe'], 'pypy')
    displayName: 'Install pypy'

  - script: choco install pypy3
    condition: eq(variables['python.exe'], 'pypy3')
    displayName: 'Install pypy3'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Invoke-WebRequest -Uri "https://bootstrap.pypa.io/get-pip.py" -OutFile "get-pip.py"
        $(python.exe) get-pip.py
    condition: startsWith(variables['python.exe'], 'pypy')
    displayName: 'Install pip'

  - script: $(python.exe) -m pip install --upgrade pip && $(python.exe) -m pip install tox
    displayName: 'Install tox'

  - script: |
      call scripts/setup-coverage-vars.bat || goto :eof
      $(python.exe) -m tox -e $(tox.env)
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'build/test-results/$(tox.env).xml'
      testRunTitle: '$(tox.env)'
    condition: succeededOrFailed()

  - script: call scripts\upload-coverage.bat
    displayName: 'Upload coverage'
    condition: eq(variables['PYTEST_COVERAGE'], '1')
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
      PYTEST_CODECOV_NAME: $(tox.env)
